### PR TITLE
add SONiC support

### PR DESCRIPTION
**Pull request by xieyangxu**

### CODE REVIEW

**Comment by xieyangxu** [comment]
Resolve #8

**Comment by ratulm** [comment]
@Ashlippers - SONiC interfaces are not supported? (How come?)

**Comment by xieyangxu** [comment]
My Batfish version (commit be9bdbb914ecbcee06260ce43d337d1bd632b0dd, which is 2 weeks old) does not report SONiC interfaces in defined structures.

**Comment by ratulm** [comment]
ah, right, those interfaces can be in config_db.json, and Batfish doesn't track structures in JSON files.

**Pull request merged**
